manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: grassfedreeve
      url-base: https://github.com/grassfedreeve
    - name: george-norton
      url-base: https://github.com/george-norton  
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: svalboard-zmk-module
      remote: grassfedreeve
      revision: trackballs
    - name: zmk-driver-pmw3360
      remote: george-norton
      revision: main            
  self:
    path: config
