manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: grassfedreeve
      url-base: https://github.com/grassfedreeve
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: svalboard-zmk-module
      remote: grassfedreeve
      revision: test
    - name: zmk-driver-pmw3360
      remote: grassfedreeve
      revision: main            
  self:
    path: config
